/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Nov-2019 13:04:53 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Join_Activity]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Join] DROP CONSTRAINT [FK_Join_Activity]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Perform_Donation]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Perform] DROP CONSTRAINT [FK_Perform_Donation]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Activity]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Activity]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Donation]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Donation]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Join]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Join]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Perform]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Perform]
GO

/* Create Tables */

CREATE TABLE [Activity]
(
	[Activityname] varchar(50) NULL,
	[Activitydate] varchar(50) NULL,
	[Maxperson] int NULL,
	[ActivityID] int NOT NULL
)
GO

CREATE TABLE [Donation]
(
	[Donateamount] float NULL,
	[DonationID] int NOT NULL
)
GO

CREATE TABLE [Alumni]
(
	[UserID] varchar(50) NOT NULL,
	[TotalActivity] int NULL,
	[CreditScore] int NULL
)
GO

CREATE TABLE [Join]
(
	[ActivityID] int NULL
)
GO

CREATE TABLE [Perform]
(
	[DonationID] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Activity] 
 ADD CONSTRAINT [PK_Activity]
	PRIMARY KEY CLUSTERED ([ActivityID] ASC)
GO

ALTER TABLE [Donation] 
 ADD CONSTRAINT [PK_Donation]
	PRIMARY KEY CLUSTERED ([DonationID] ASC)
GO

ALTER TABLE [Alumni] 
 ADD CONSTRAINT [PK_Alumni]
	PRIMARY KEY CLUSTERED ([UserID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Join] ADD CONSTRAINT [FK_Join_Activity]
	FOREIGN KEY ([ActivityID]) REFERENCES [Activity] ([ActivityID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Perform] ADD CONSTRAINT [FK_Perform_Donation]
	FOREIGN KEY ([DonationID]) REFERENCES [Donation] ([DonationID]) ON DELETE No Action ON UPDATE No Action
GO
