///////////////////////////////////////////////////////////
//  Activity.cs
//  Implementation of the Class Activity
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2019 02:12:00
//  Original author: jasim
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Business {
	public class Activity {

		private string activityName;
		private string activityDate;
		private int totalParticipant;

		public Activity(){

		}

		~Activity(){

		}


	}//end Activity

}//end namespace Business