///////////////////////////////////////////////////////////
//  Donation.cs
//  Implementation of the Class Donation
//  Generated by Enterprise Architect
//  Created on:      20-Nov-2019 02:12:02
//  Original author: jasim
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DataSetTableAdapters;



namespace Business {
	public class Donation {

		public float DonateAmount;
       

        public Donation(){

		}

        public Donation(float DonateAmount)
        {
            this.DonateAmount = DonateAmount;
        }
        ~Donation(){

		}
        public void newDonation(float amount)
        {
            this.DonateAmount = amount;
        }

        public Donation clone(float donateAmount)
        {
            Donation other = (Donation)this.MemberwiseClone();
            other.DonateAmount = donateAmount;
            return other;
        }

        public void AddDonation(Donation currentDonation)
        {
            DonationTableAdapter adapter = new DonationTableAdapter();
            adapter.MakeDonation(
                currentDonation.DonateAmount);
        }
    }//end Donation

}//end namespace Business